server {
    listen 80;
    listen [::]:80;
    server_name weouthere.ussyco.de;

    location /.well-known/acme-challenge/ {
        root /home/mojo/web/out;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name weouthere.ussyco.de;

    ssl_certificate /etc/letsencrypt/live/ussyco.de/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ussyco.de/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    root /home/mojo/projects/show/we-out-here/site;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
